"""Initial migration

Revision ID: 872a40d28df0
Revises: 
Create Date: 2026-05-01 14:06:45.265424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872a40d28df0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('ADOPTER', 'DONOR', 'BOTH', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified_email', sa.Boolean(), nullable=False),
    sa.Column('is_verified_phone', sa.Boolean(), nullable=False),
    sa.Column('verification_level', sa.Integer(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('reputation_count', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('adopter_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('housing_type', sa.Enum('HOUSE', 'APARTMENT', 'RURAL', name='housingtype'), nullable=True),
    sa.Column('has_yard', sa.Boolean(), nullable=False),
    sa.Column('yard_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='yardsize'), nullable=True),
    sa.Column('has_other_pets', sa.Boolean(), nullable=False),
    sa.Column('other_pets_details', sa.Text(), nullable=True),
    sa.Column('has_children', sa.Boolean(), nullable=False),
    sa.Column('children_ages', sa.String(length=100), nullable=True),
    sa.Column('daily_hours_alone', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.Enum('FIRST_TIME', 'SOME', 'EXPERIENCED', name='experiencelevel'), nullable=True),
    sa.Column('preferred_species', sa.Enum('DOG', 'CAT', 'BOTH', name='preferredspecies'), nullable=True),
    sa.Column('preferred_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'ANY', name='preferredsize'), nullable=True),
    sa.Column('preferred_age_min', sa.Integer(), nullable=True),
    sa.Column('preferred_age_max', sa.Integer(), nullable=True),
    sa.Column('preferred_energy_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'ANY', name='energylevel'), nullable=True),
    sa.Column('max_distance_km', sa.Integer(), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('donor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_organization', sa.Boolean(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('total_pets_donated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', name='species'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='petsize'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('is_neutered', sa.Boolean(), nullable=False),
    sa.Column('is_vaccinated', sa.Boolean(), nullable=False),
    sa.Column('vaccination_details', sa.Text(), nullable=True),
    sa.Column('health_status', sa.Text(), nullable=True),
    sa.Column('energy_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='petenergylevel'), nullable=False),
    sa.Column('good_with_kids', sa.Boolean(), nullable=True),
    sa.Column('good_with_pets', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('requires_yard', sa.Boolean(), nullable=False),
    sa.Column('requires_experience', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'MATCHED', 'ADOPTED', 'REMOVED', name='petstatus'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_donor_id'), 'pets', ['donor_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('adopter_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('adopter_message', sa.Text(), nullable=True),
    sa.Column('donor_response', sa.Text(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adopter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_adopter_id'), 'matches', ['adopter_id'], unique=False)
    op.create_index(op.f('ix_matches_donor_id'), 'matches', ['donor_id'], unique=False)
    op.create_index(op.f('ix_matches_pet_id'), 'matches', ['pet_id'], unique=False)
    op.create_table('pet_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_photos_pet_id'), 'pet_photos', ['pet_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=True),
    sa.Column('reported_pet_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('FRAUD', 'ABUSE', 'FAKE_LISTING', 'INAPPROPRIATE', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWING', 'RESOLVED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('adopter_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adopter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('post_adoption_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('adopter_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('status_note', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('donor_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adopter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_adoption_evidence_match_id'), 'post_adoption_evidence', ['match_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_post_adoption_evidence_match_id'), table_name='post_adoption_evidence')
    op.drop_table('post_adoption_evidence')
    op.drop_table('chats')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_pet_photos_pet_id'), table_name='pet_photos')
    op.drop_table('pet_photos')
    op.drop_index(op.f('ix_matches_pet_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_donor_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_adopter_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_pets_donor_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_table('donor_profiles')
    op.drop_table('adopter_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
